<a href="https://colab.research.google.com/github/yujiunzou/supply-chain-analytics/blob/main/02_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Supply Chain Data Cleaning

This notebook cleans and standardizes the seven supply-chain datasets based on the issues identified during data profiling.

The raw datasets are preserved without modification. Clean copies are created for all transformations.

Load Raw Data and Create Copies

In [1]:
import pandas as pd
import numpy as np

orders = pd.read_csv("/content/orders.csv")
freight_rates = pd.read_csv("/content/freight_rates.csv")
plant_ports = pd.read_csv("/content/plant_ports.csv")
products_per_plant = pd.read_csv("/content/products_per_plant.csv")
vmi_customers = pd.read_csv("/content/vmi_customers.csv")
warehouse_capacities = pd.read_csv("/content/warehouse_capacities.csv")
warehouse_costs = pd.read_csv("/content/warehouse_costs.csv")

orders_clean = orders.copy()
freight_rates_clean = freight_rates.copy()
plant_ports_clean = plant_ports.copy()
products_per_plant_clean = products_per_plant.copy()
vmi_customers_clean = vmi_customers.copy()
warehouse_capacities_clean = warehouse_capacities.copy()
warehouse_costs_clean = warehouse_costs.copy()

In [2]:
print("=" * 60)
print(f"order_clean columns and data type")
print("=" * 60)
print(orders_clean.info())

============================================================
order_clean columns and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9215 entries, 0 to 9214
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              9215 non-null   float64
 1   order_date            9215 non-null   object
 2   origin_port           9215 non-null   object
 3   carrier               9215 non-null   object
 4   tpt                   9215 non-null   int64
 5   service_level         9215 non-null   object
 6   ship_ahead_day_count  9215 non-null   int64
 7   ship_late_day_count   9215 non-null   int64
 8   customer              9215 non-null   object
 9   product_id            9215 non-null   int64
 10  plant_code            9215 non-null   object
 11  destination_port      9215 non-null   object
 12  unit_quantity         9215 non-null   int64
 13  weight                9215 non-null   float64
dtypes: float64(2), int64(5), object(7)
memory usage: 1008.0+ KB
None

In [3]:
print("=" * 60)
print(f"freight_rates_clean and data type")
print("=" * 60)
print(freight_rates_clean.info())

============================================================
freight_rates_clean and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540 entries, 0 to 1539
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   carrier       1540 non-null   object
 1   orig_port_cd  1540 non-null   object
 2   dest_port_cd  1540 non-null   object
 3   minm_wgh_qty  1540 non-null   float64
 4   max_wgh_qty   1540 non-null   float64
 5   svc_cd        1540 non-null   object
 6   minimum_cost  1540 non-null   float64
 7   rate          1540 non-null   float64
 8   mode_dsc      1540 non-null   object
 9   tpt_day_cnt   1540 non-null   int64
 10  carrier_type  1540 non-null   object
dtypes: float64(4), int64(1), object(6)
memory usage: 132.5+ KB
None

In [4]:
print("=" * 60)
print(f"plant_ports_clean and data type")
print("=" * 60)
print(plant_ports_clean.info())

print("=" * 60)
print(f"plant_ports_clean and data type")
print("=" * 60)
print(plant_ports_clean.info())

============================================================
plant_ports_clean and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   plant_code  22 non-null     object
 1   port        22 non-null     object
dtypes: object(2)
memory usage: 484.0+ bytes
None
============================================================
plant_ports_clean and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   plant_code  22 non-null     object
 1   port        22 non-null     object
dtypes: object(2)
memory usage: 484.0+ bytes
None

In [5]:
print("=" * 60)
print(f"vmi_customers_clean and data type")
print("=" * 60)
print(vmi_customers_clean.info())

============================================================
vmi_customers_clean and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   plant_code  14 non-null     object
 1   customers   14 non-null     object
dtypes: object(2)
memory usage: 356.0+ bytes
None

In [6]:
print("=" * 60)
print(f"warehouse_capacities_clean and data type")
print("=" * 60)
print(warehouse_capacities_clean.info())

print("=" * 60)
print(f"warehouse_costs_clean and data type")
print("=" * 60)
print(warehouse_costs_clean.info())

============================================================
warehouse_capacities_clean and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   plant_id        19 non-null     object
 1   daily_capacity  19 non-null     int64
dtypes: int64(1), object(1)
memory usage: 436.0+ bytes
None
============================================================
warehouse_costs_clean and data type
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   wh         19 non-null     object
 1   cost_unit  19 non-null     float64
dtypes: float64(1), object(1)
memory usage: 436.0+ bytes
None

##1.Standardize Column Names

In [7]:
# standardize order column names
orders_clean = orders_clean.rename(columns={
    "tpt": "transport_days"
})

# standardize freight-rate columm names
freight_rates_clean = freight_rates_clean.rename(columns={
    "orig_port_cd": "origin_port",
    "dest_port_cd": "destination_port",
    "minm_wgh_qty": "min_weight",
    "max_wgh_qty": "max_weight",
    "svc_cd": "service_level",
    "tpt_day_cnt": "transport_days",
    "minimum_cost": "min_cost",
    "mode_dsc": "transport_mode"
})

# Standardize plant identifier columns
warehouse_capacities_clean = warehouse_capacities_clean.rename(columns={
    "plant_id": "plant_code"
})
warehouse_costs_clean = warehouse_costs_clean.rename(columns={
    "wh": "plant_code"
})

# Standardize VMI customer column name
vmi_customers_clean = vmi_customers_clean.rename(columns={
    "customers": "customer"
})

In [8]:
orders_clean.head()

,order_id,order_date,origin_port,carrier,transport_days,service_level,ship_ahead_day_count,ship_late_day_count,customer,product_id,plant_code,destination_port,unit_quantity,weight
0,1.447296e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30
1,1.447158e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94
2,1.447139e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20
3,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16
4,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34

In [9]:
clean_tables = {
    "Orders": orders_clean,
    "Freight Rates": freight_rates_clean,
    "Plant Ports": plant_ports_clean,
    "Products per Plant": products_per_plant_clean,
    "VMI Customers": vmi_customers_clean,
    "Warehouse Capacities": warehouse_capacities_clean,
    "Warehouse Costs": warehouse_costs_clean
}

for table_name, df in clean_tables.items():
    print(f"\n{table_name}")
    print(df.columns.tolist())

Orders
['order_id', 'order_date', 'origin_port', 'carrier', 'transport_days', 'service_level', 'ship_ahead_day_count', 'ship_late_day_count', 'customer', 'product_id', 'plant_code', 'destination_port', 'unit_quantity', 'weight']

Freight Rates
['carrier', 'origin_port', 'destination_port', 'min_weight', 'max_weight', 'service_level', 'min_cost', 'rate', 'transport_mode', 'transport_days', 'carrier_type']

Plant Ports
['plant_code', 'port']

Products per Plant
['plant_code', 'product_id']

VMI Customers
['plant_code', 'customer']

Warehouse Capacities
['plant_code', 'daily_capacity']

Warehouse Costs
['plant_code', 'cost_unit']

##2.Convert Data Types

1. order

In [10]:
# convert data type
orders_clean["order_id"] = (
    orders_clean["order_id"]
    .astype("string")
    .str.strip()
)
orders_clean["order_date"] = pd.to_datetime(orders_clean["order_date"], errors="coerce")

orders_clean["product_id"] = orders_clean["product_id"].astype("string")
orders_clean["transport_days"] = orders_clean["transport_days"].astype(int)

# Convert categorical identifiers to string
orders_string_columns = [
    "origin_port",
    "carrier",
    "service_level",
    "customer",
    "plant_code",
    "destination_port"
]

orders_clean[orders_string_columns] = (
    orders_clean[orders_string_columns]
    .astype("string")
)

In [11]:
orders_clean.head()

,order_id,order_date,origin_port,carrier,transport_days,service_level,ship_ahead_day_count,ship_late_day_count,customer,product_id,plant_code,destination_port,unit_quantity,weight
0,1447296446.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30
1,1447158014.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94
2,1447138898.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20
3,1447363527.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16
4,1447363980.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34

In [12]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9215 entries, 0 to 9214
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              9215 non-null   string
 1   order_date            9215 non-null   datetime64[ns]
 2   origin_port           9215 non-null   string
 3   carrier               9215 non-null   string
 4   transport_days        9215 non-null   int64
 5   service_level         9215 non-null   string
 6   ship_ahead_day_count  9215 non-null   int64
 7   ship_late_day_count   9215 non-null   int64
 8   customer              9215 non-null   string
 9   product_id            9215 non-null   string
 10  plant_code            9215 non-null   string
 11  destination_port      9215 non-null   string
 12  unit_quantity         9215 non-null   int64
 13  weight                9215 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(4), string(8)
memory usage: 1008.0 KB

2.Freight Rates

In [13]:
freight_string_columns = [
    "carrier",
    "origin_port",
    "destination_port",
    "service_level",
    "transport_mode",
    "carrier_type"
]

freight_rates_clean[freight_string_columns] = (
    freight_rates_clean[freight_string_columns]
    .astype("string")
)

In [14]:
freight_rates_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540 entries, 0 to 1539
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   carrier           1540 non-null   string
 1   origin_port       1540 non-null   string
 2   destination_port  1540 non-null   string
 3   min_weight        1540 non-null   float64
 4   max_weight        1540 non-null   float64
 5   service_level     1540 non-null   string
 6   min_cost          1540 non-null   float64
 7   rate              1540 non-null   float64
 8   transport_mode    1540 non-null   string
 9   transport_days    1540 non-null   int64
 10  carrier_type      1540 non-null   string
dtypes: float64(4), int64(1), string(6)
memory usage: 132.5 KB

3.Plant Ports

In [15]:
plant_ports_clean[["plant_code", "port"]] = (
    plant_ports_clean[["plant_code", "port"]]
    .astype("string")
)

4.Products per Plant

In [16]:
products_per_plant_clean["plant_code"] = (
    products_per_plant_clean["plant_code"]
    .astype("string")
)

products_per_plant_clean["product_id"] = (
    products_per_plant_clean["product_id"]
    .astype("Int64")
    .astype("string")
)

5.VMI Customers

In [17]:
vmi_customers_clean[["plant_code", "customer"]] = (
    vmi_customers_clean[["plant_code", "customer"]]
    .astype("string")
)

6.Warehouse Capacities

In [18]:
warehouse_capacities_clean["plant_code"] = (
    warehouse_capacities_clean["plant_code"]
    .astype("string")
)

7.Warehouse Costs

In [19]:
warehouse_costs_clean["plant_code"] = (
    warehouse_costs_clean["plant_code"]
    .astype("string")
)

In [20]:
clean_tables = {
    "Orders": orders_clean,
    "Freight Rates": freight_rates_clean,
    "Plant Ports": plant_ports_clean,
    "Products per Plant": products_per_plant_clean,
    "VMI Customers": vmi_customers_clean,
    "Warehouse Capacities": warehouse_capacities_clean,
    "Warehouse Costs": warehouse_costs_clean
}

In [21]:
for table_name, df in clean_tables.items():
    print(f"\n{'=' * 50}")
    print(table_name)
    print("=" * 50)
    print(df.dtypes)

==================================================
Orders
==================================================
order_id                string[python]
order_date              datetime64[ns]
origin_port             string[python]
carrier                 string[python]
transport_days                   int64
service_level           string[python]
ship_ahead_day_count             int64
ship_late_day_count              int64
customer                string[python]
product_id              string[python]
plant_code              string[python]
destination_port        string[python]
unit_quantity                    int64
weight                         float64
dtype: object

==================================================
Freight Rates
==================================================
carrier             string[python]
origin_port         string[python]
destination_port    string[python]
min_weight                 float64
max_weight                 float64
service_level       string[python]
min_cost                   float64
rate                       float64
transport_mode      string[python]
transport_days               int64
carrier_type        string[python]
dtype: object

==================================================
Plant Ports
==================================================
plant_code    string[python]
port          string[python]
dtype: object

==================================================
Products per Plant
==================================================
plant_code    string[python]
product_id    string[python]
dtype: object

==================================================
VMI Customers
==================================================
plant_code    string[python]
customer      string[python]
dtype: object

==================================================
Warehouse Capacities
==================================================
plant_code        string[python]
daily_capacity             int64
dtype: object

==================================================
Warehouse Costs
==================================================
plant_code    string[python]
cost_unit            float64
dtype: object

##3.Standardize Text Values

In [23]:
text_cleaning_summary = []

for table_name, df in clean_tables.items():

    # Select all string columns
    string_columns = df.select_dtypes(
        include="string"
    ).columns

    for column in string_columns:
        before = df[column].copy()

        # Remove surrounding spaces and standardize uppercase
        df[column] = (
            df[column]
            .str.strip()
            .str.upper()
        )

        changed_count = (
            before.ne(df[column])
            .fillna(False)
            .sum()
        )

        text_cleaning_summary.append({
            "table": table_name,
            "column": column,
            "changed_values": changed_count
        })

In [24]:
text_cleaning_summary = pd.DataFrame(text_cleaning_summary)
display(text_cleaning_summary)

                   table            column  changed_values
0                 Orders          order_id               0
1                 Orders       origin_port               0
2                 Orders           carrier               0
3                 Orders     service_level               0
4                 Orders          customer               0
5                 Orders        product_id               0
6                 Orders        plant_code               0
7                 Orders  destination_port               0
8          Freight Rates           carrier               0
9          Freight Rates       origin_port               0
10         Freight Rates  destination_port               0
11         Freight Rates     service_level               0
12         Freight Rates    transport_mode               0
13         Freight Rates      carrier_type               0
14           Plant Ports        plant_code               0
15           Plant Ports              port               0
16    Products per Plant        plant_code               0
17    Products per Plant        product_id               0
18         VMI Customers        plant_code               0
19         VMI Customers          customer               0
20  Warehouse Capacities        plant_code               0
21       Warehouse Costs        plant_code               0

In [25]:
columns_to_check = {
    "Orders - Origin Port": orders_clean["origin_port"],
    "Orders - Carrier": orders_clean["carrier"],
    "Orders - Service Level": orders_clean["service_level"],
    "Orders - Plant": orders_clean["plant_code"],
    "Freight - Transport Mode": freight_rates_clean["transport_mode"],
    "Freight - Service Level": freight_rates_clean["service_level"]
}

for name, series in columns_to_check.items():
    print(f"\n{name}")
    print(sorted(series.dropna().unique()))

Orders - Origin Port
['PORT04', 'PORT05', 'PORT09']

Orders - Carrier
['V444_0', 'V444_1', 'V44_3']

Orders - Service Level
['CRF', 'DTD', 'DTP']

Orders - Plant
['PLANT03', 'PLANT04', 'PLANT08', 'PLANT09', 'PLANT12', 'PLANT13', 'PLANT16']

Freight - Transport Mode
['AIR', 'GROUND']

Freight - Service Level
['DTD', 'DTP']

##4.Handle Duplicate Records

In [26]:
duplicate_summary = []

for table_name, df in clean_tables.items():
    duplicate_count = df.duplicated().sum()

    duplicate_summary.append({
        "table": table_name,
        "rows_before": len(df),
        "duplicate_rows": duplicate_count
    })

duplicate_summary = pd.DataFrame(duplicate_summary)

display(duplicate_summary)

                  table  rows_before  duplicate_rows
0                Orders         9215               0
1         Freight Rates         1540               3
2           Plant Ports           22               0
3    Products per Plant         2036               0
4         VMI Customers           14               0
5  Warehouse Capacities           19               0
6       Warehouse Costs           19               0

In [27]:
freight_duplicates = freight_rates_clean[
    freight_rates_clean.duplicated(
        keep=False
    )
].sort_values(
    by=[
        "carrier",
        "origin_port",
        "destination_port",
        "service_level",
        "min_weight",
        "max_weight"
    ]
)

display(freight_duplicates)

,carrier,origin_port,destination_port,min_weight,max_weight,service_level,min_cost,rate,transport_mode,transport_days,carrier_type
1504,V444_0,PORT03,PORT09,0.0,5000.0,DTD,27.2024,13.2024,GROUND,1,V88888888_0
1505,V444_0,PORT03,PORT09,0.0,5000.0,DTD,27.2024,13.2024,GROUND,1,V88888888_0
1510,V444_0,PORT03,PORT09,0.0,5000.0,DTD,27.2024,13.2024,GROUND,1,V88888888_0
1492,V444_5,PORT03,PORT09,0.0,5000.0,DTD,27.2024,9.2024,GROUND,1,V88888888_0
1494,V444_5,PORT03,PORT09,0.0,5000.0,DTD,27.2024,9.2024,GROUND,1,V88888888_0

In [28]:
freight_rows_before = len(freight_rates_clean)
freight_rates_clean = (
    freight_rates_clean
    .drop_duplicates()
    .reset_index(drop=True))

freight_rows_after = len(freight_rates_clean)

print("Rows before:", freight_rows_before)
print("Rows after:", freight_rows_after)

Rows before: 1540
Rows after: 1537

In [29]:
clean_tables["Freight Rates"] = freight_rates_clean
for table_name, df in clean_tables.items():
    print(
        f"{table_name}: "
        f"{df.duplicated().sum()} duplicates"
    )

Orders: 0 duplicates
Freight Rates: 0 duplicates
Plant Ports: 0 duplicates
Products per Plant: 0 duplicates
VMI Customers: 0 duplicates
Warehouse Capacities: 0 duplicates
Warehouse Costs: 0 duplicates

##5.Numeric Value Validation

In [30]:
numeric_validation = {
    # Orders
    "Negative transport days":
        (orders_clean["transport_days"] < 0).sum(),

    "Negative ship ahead days":
        (orders_clean["ship_ahead_day_count"] < 0).sum(),

    "Negative ship late days":
        (orders_clean["ship_late_day_count"] < 0).sum(),

    "Non-positive unit quantity":
        (orders_clean["unit_quantity"] <= 0).sum(),

    "Non-positive weight":
        (orders_clean["weight"] <= 0).sum(),

    # Freight Rates
    "Negative freight transport days":
        (freight_rates_clean["transport_days"] < 0).sum(),

    "Negative minimum cost":
        (freight_rates_clean["min_cost"] < 0).sum(),

    "Negative freight rate":
        (freight_rates_clean["rate"] < 0).sum(),

    "Invalid weight range":
        (
            freight_rates_clean["min_weight"]
            > freight_rates_clean["max_weight"]
        ).sum(),

    # Warehouse
    "Non-positive warehouse capacity":
        (warehouse_capacities_clean["daily_capacity"] <= 0).sum(),

    "Non-positive warehouse cost":
        (warehouse_costs_clean["cost_unit"] <= 0).sum()
}

numeric_validation_df = pd.DataFrame(
    numeric_validation.items(),
    columns=["validation_check", "issue_count"]
)

display(numeric_validation_df)

                   validation_check  issue_count
0           Negative transport days            0
1          Negative ship ahead days            0
2           Negative ship late days            0
3        Non-positive unit quantity            0
4               Non-positive weight            2
5   Negative freight transport days            0
6             Negative minimum cost            0
7             Negative freight rate            0
8              Invalid weight range            0
9   Non-positive warehouse capacity            0
10      Non-positive warehouse cost            0

In [31]:
invalid_weight_orders = orders_clean[
    orders_clean["weight"] <= 0
]

display(invalid_weight_orders)

,order_id,order_date,origin_port,carrier,transport_days,service_level,ship_ahead_day_count,ship_late_day_count,customer,product_id,plant_code,destination_port,unit_quantity,weight
4638,1447215484.7,2013-05-26,PORT04,V444_0,2,DTP,3,0,V55555555_5,1699946,PLANT03,PORT09,348,0.0
5592,1447336276.7,2013-05-26,PORT04,V444_0,2,DTP,3,0,V555555_6,1658528,PLANT03,PORT09,361,0.0

In [39]:
# Flag orders with valid shipment weight
orders_clean["weight_valid"] = (
    orders_clean["weight"] > 0
)

print(orders_clean["weight_valid"].value_counts())

clean_tables["Orders"] = orders_clean

#只保留weight>0,共9213筆,有需要實在使用
valid_weight_orders = orders_clean[
    orders_clean["weight_valid"]].copy()
valid_weight_orders.info()

weight_valid
True     9213
False       2
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 9213 entries, 0 to 9214
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              9213 non-null   string
 1   order_date            9213 non-null   datetime64[ns]
 2   origin_port           9213 non-null   string
 3   carrier               9213 non-null   string
 4   transport_days        9213 non-null   int64
 5   service_level         9213 non-null   string
 6   ship_ahead_day_count  9213 non-null   int64
 7   ship_late_day_count   9213 non-null   int64
 8   customer              9213 non-null   string
 9   product_id            9213 non-null   string
 10  plant_code            9213 non-null   string
 11  destination_port      9213 non-null   string
 12  unit_quantity         9213 non-null   int64
 13  weight                9213 non-null   float64
 14  weight_valid          9213 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(4), string(8)
memory usage: 1.1 MB

In [40]:
print("orders_clean:", len(orders_clean))
print("valid_weight_orders:", len(valid_weight_orders))

orders_clean: 9215
valid_weight_orders: 9213

In [37]:
# Validate shipping-window values
invalid_shipping_windows = orders_clean[
    (orders_clean["ship_ahead_day_count"] < 0) |
    (orders_clean["ship_late_day_count"] < 0)
]

print(
    "Invalid shipping window records:",
    len(invalid_shipping_windows)
)

display(invalid_shipping_windows)

Invalid shipping window records: 0

Empty DataFrame
Columns: [order_id, order_date, origin_port, carrier, transport_days, service_level, ship_ahead_day_count, ship_late_day_count, customer, product_id, plant_code, destination_port, unit_quantity, weight, weight_valid]
Index: []

### Numeric Validation Summary

- No negative values were found in transportation days, shipping-window fields, quantities, freight costs, freight rates, warehouse capacities, or warehouse costs.
- No invalid freight weight ranges were identified.
- Two orders contained zero shipment weight.
- These records were retained and flagged using `weight_valid = False`.
- They will be excluded only from weight-based freight analysis.
- Ship-ahead and ship-late values represent an acceptable shipping window and were therefore retained.

In [38]:
orders_clean.head()

,order_id,order_date,origin_port,carrier,transport_days,service_level,ship_ahead_day_count,ship_late_day_count,customer,product_id,plant_code,destination_port,unit_quantity,weight,weight_valid
0,1447296446.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30,True
1,1447158014.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94,True
2,1447138898.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20,True
3,1447363527.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16,True
4,1447363980.7,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34,True

##6.Key and Referential Integrity Validation

In [41]:
key_validation = {
    "Duplicate order_id":
        orders_clean["order_id"].duplicated().sum(),

    "Duplicate plant-port combinations":
        plant_ports_clean.duplicated(
            subset=["plant_code", "port"]
        ).sum(),

    "Duplicate plant-product combinations":
        products_per_plant_clean.duplicated(
            subset=["plant_code", "product_id"]
        ).sum(),

    "Duplicate VMI plant-customer combinations":
        vmi_customers_clean.duplicated(
            subset=["plant_code", "customer"]
        ).sum(),

    "Duplicate capacity plant_code":
        warehouse_capacities_clean["plant_code"]
        .duplicated().sum(),

    "Duplicate cost plant_code":
        warehouse_costs_clean["plant_code"]
        .duplicated().sum()
}

key_validation_df = pd.DataFrame(
    key_validation.items(),
    columns=["validation_check", "issue_count"]
)

display(key_validation_df)

                            validation_check  issue_count
0                         Duplicate order_id            0
1          Duplicate plant-port combinations            0
2       Duplicate plant-product combinations            0
3  Duplicate VMI plant-customer combinations            0
4              Duplicate capacity plant_code            0
5                  Duplicate cost plant_code            0

In [42]:
plant_reference_checks = {
    "Orders plants missing from capacities":
        (~orders_clean["plant_code"].isin(
            warehouse_capacities_clean["plant_code"]
        )).sum(),

    "Orders plants missing from costs":
        (~orders_clean["plant_code"].isin(
            warehouse_costs_clean["plant_code"]
        )).sum(),

    "Orders plants missing from plant ports":
        (~orders_clean["plant_code"].isin(
            plant_ports_clean["plant_code"]
        )).sum()
}

plant_reference_df = pd.DataFrame(
    plant_reference_checks.items(),
    columns=["validation_check", "issue_count"]
)

display(plant_reference_df)

                         validation_check  issue_count
0   Orders plants missing from capacities            0
1        Orders plants missing from costs            0
2  Orders plants missing from plant ports            0

In [43]:
valid_plant_products = (
    products_per_plant_clean[
        ["plant_code", "product_id"]
    ]
    .drop_duplicates()
)

invalid_order_products = (
    orders_clean
    .merge(
        valid_plant_products,
        on=["plant_code", "product_id"],
        how="left",
        indicator=True
    )
    .query("_merge == 'left_only'")
    .drop(columns="_merge")
)

print(
    "Orders with invalid plant-product combinations:",
    len(invalid_order_products)
)

display(invalid_order_products.head())

Orders with invalid plant-product combinations: 0

Empty DataFrame
Columns: [order_id, order_date, origin_port, carrier, transport_days, service_level, ship_ahead_day_count, ship_late_day_count, customer, product_id, plant_code, destination_port, unit_quantity, weight, weight_valid]
Index: []

##7.Final Validation Summary

In [44]:
clean_tables = {
    "Orders": orders_clean,
    "Freight Rates": freight_rates_clean,
    "Plant Ports": plant_ports_clean,
    "Products per Plant": products_per_plant_clean,
    "VMI Customers": vmi_customers_clean,
    "Warehouse Capacities": warehouse_capacities_clean,
    "Warehouse Costs": warehouse_costs_clean
}

In [45]:
final_table_summary = []

for table_name, df in clean_tables.items():
    final_table_summary.append({
        "table": table_name,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_values": df.isna().sum().sum(),
        "duplicate_rows": df.duplicated().sum()
    })

final_table_summary_df = pd.DataFrame(
    final_table_summary
)

display(final_table_summary_df)

                  table  rows  columns  missing_values  duplicate_rows
0                Orders  9215       15               0               0
1         Freight Rates  1537       11               0               0
2           Plant Ports    22        2               0               0
3    Products per Plant  2036        2               0               0
4         VMI Customers    14        2               0               0
5  Warehouse Capacities    19        2               0               0
6       Warehouse Costs    19        2               0               0

In [46]:
final_quality_checks = {
    "Duplicate order IDs":
        orders_clean["order_id"].duplicated().sum(),

    "Orders with zero or negative weight":
        (orders_clean["weight"] <= 0).sum(),

    "Invalid shipping windows":
        (
            (orders_clean["ship_ahead_day_count"] < 0) |
            (orders_clean["ship_late_day_count"] < 0)
        ).sum(),

    "Non-positive order quantity":
        (orders_clean["unit_quantity"] <= 0).sum(),

    "Invalid freight weight ranges":
        (
            freight_rates_clean["min_weight"]
            > freight_rates_clean["max_weight"]
        ).sum(),

    "Negative freight rates":
        (freight_rates_clean["rate"] < 0).sum(),

    "Non-positive warehouse capacities":
        (
            warehouse_capacities_clean["daily_capacity"]
            <= 0
        ).sum(),

    "Non-positive warehouse costs":
        (
            warehouse_costs_clean["cost_unit"]
            <= 0
        ).sum(),

    "Orders missing capacity reference":
        (
            ~orders_clean["plant_code"].isin(
                warehouse_capacities_clean["plant_code"]
            )
        ).sum(),

    "Orders missing cost reference":
        (
            ~orders_clean["plant_code"].isin(
                warehouse_costs_clean["plant_code"]
            )
        ).sum(),

    "Orders missing plant-port reference":
        (
            ~orders_clean["plant_code"].isin(
                plant_ports_clean["plant_code"]
            )
        ).sum(),

    "Invalid plant-product combinations":
        len(invalid_order_products)
}

final_quality_df = pd.DataFrame(
    final_quality_checks.items(),
    columns=["validation_check", "issue_count"]
)

display(final_quality_df)

                       validation_check  issue_count
0                   Duplicate order IDs            0
1   Orders with zero or negative weight            2
2              Invalid shipping windows            0
3           Non-positive order quantity            0
4         Invalid freight weight ranges            0
5                Negative freight rates            0
6     Non-positive warehouse capacities            0
7          Non-positive warehouse costs            0
8     Orders missing capacity reference            0
9         Orders missing cost reference            0
10  Orders missing plant-port reference            0
11   Invalid plant-product combinations            0

# Data Cleaning Summary

### 1. 建立資料副本

使用 `.copy()` 建立清理用的 DataFrame，避免直接修改原始資料。

### 2. 統一欄位名稱

將不同資料表中代表相同概念的欄位統一命名，例如：

- `tpt`、`tpt_day_cnt` → `transport_days`
- `orig_port_cd` → `origin_port`
- `dest_port_cd` → `destination_port`
- `plant_id`、`wh` → `plant_code`
- `customers` → `customer`

### 3. 修正資料型態

- 將 `order_date` 轉換為日期格式。
- 將訂單、產品、工廠、港口、客戶及其他類別欄位轉為字串格式。
- 將數量、天數及產能欄位轉為整數格式。
- 將重量、費率及成本欄位轉為浮點數格式。
- 將 `order_id` 以字串格式保存，避免包含小數的識別碼被四捨五入或截斷。

### 4. 標準化文字資料

針對所有字串欄位：

- 移除文字前後的空格。
- 將代碼及類別值統一轉換為大寫。

例如：

- ` plant03 ` → `PLANT03`
- `air` → `AIR`

### 5. 處理重複資料

- 在 Freight Rates 資料表中發現 3 筆額外的完全重複資料。
- 使用 `.drop_duplicates()` 移除重複資料。
- Freight Rates 的資料筆數由 1,540 筆減少為 1,537 筆。
- 其他資料表未發現完全重複的紀錄。

### 6. 驗證數值合理性

檢查以下可能的資料品質問題：

- 負數的運輸天數
- 負數的提前或延遲出貨天數
- 非正數的訂購數量
- 負數的最低成本或運費率
- 最小重量大於最大重量
- 非正數的倉庫產能
- 非正數的倉庫處理成本

除了 2 筆零重量訂單外，其餘數值檢查皆通過。

### 7. 標記零重量訂單

- 原始資料中有 2 筆訂單的 `weight` 為 0。
- 保留這 2 筆訂單，避免影響訂單數量、客戶、產品及工廠分析。
- 新增 `weight_valid` 欄位標記重量是否有效：
  - `True`：重量大於 0，可以進行重量與運費分析。
  - `False`：重量等於 0，不納入重量與運費分析。
- 完整訂單分析使用 `orders_clean`。
- 重量與運費分析使用 `valid_weight_orders`。

### 8. 驗證出貨時間範圍

- 確認 `ship_ahead_day_count` 與 `ship_late_day_count` 沒有負數。
- 兩個欄位同時大於 0 不代表資料衝突，而是表示訂單允許的提前與延遲出貨範圍。
- 因此保留原始的 shipping-window 數值。

### 9. 驗證 Key 與資料表關聯

針對各資料表的 Primary Key、Composite Key 及表格間的關聯進行驗證：

- 檢查 `orders` 中的 `order_id` 是否唯一。
- 檢查 `plant_ports` 中的 `plant_code + port` 組合是否重複。
- 檢查 `products_per_plant` 中的 `plant_code + product_id` 組合是否重複。
- 檢查 `vmi_customers` 中的 `plant_code + customer` 組合是否重複。
- 檢查 Warehouse Capacities 與 Warehouse Costs 中的 `plant_code` 是否唯一。
- Freight Rates 沒有單一欄位可以作為唯一識別值，因此使用 carrier、路線、服務類型、運輸方式及重量區間組成 Composite Key 進行檢查。
- 確認訂單中的工廠能在產能、倉庫成本及工廠港口資料表中找到。
- 確認訂單中的 `plant_code + product_id` 組合能否對應至 Products per Plant 資料表。
- 由於 Orders 為歷史訂單，而其他資料表代表目前的供應鏈限制，因此無法對應的歷史組合將先保留並記錄，不會直接刪除。

### 10. 最終資料品質驗證

完成資料清理後，再次對七個資料表進行整體驗證：

- 確認各資料表清理後的資料筆數與欄位數。
- 再次檢查 missing values 與完全重複資料。
- 確認 `order_id` 及各資料表的 Composite Key 沒有非預期重複。
- 再次檢查負數、零值及不合理的重量區間。
- 確認工廠、產能、成本、港口及產品之間的資料關聯。
- Freight Rates 移除 3 筆完全重複資料後，由 1,540 筆減少為 1,537 筆。
- Orders 保留完整的 9,215 筆資料。
- 其中 2 筆零重量訂單以 `weight_valid = False` 標記，只在重量與運費分析時排除。
- 清理後的完整訂單主表為 `orders_clean`，重量與運費分析使用 `valid_weight_orders`。
- 完成驗證後，將清理結果匯出至 cleaned data 資料夾，供後續 EDA、SQL、成本分析及 Power BI 使用。